intersectpoly: intersectpoly.cc
	g++ -std=c++17 -O3 -Wall -Wextra -pedantic -Wredundant-decls -Wdisabled-optimization -Wctor-dtor-privacy -Wnon-virtual-dtor -Woverloaded-virtual -Wsign-promo -Wold-style-cast -g -o $@ $^

clean:
	rm intersectpoly
